'use strict';
const advisors={
 mayb:{name:'Mayb Maia',role:'Pessoas e Cultura',photo:'mayb-maia.webp',experience:'20+ anos de experiência em Recursos Humanos',summary:'Psicóloga e consultora com experiência em gestão de pessoas, desenvolvimento de lideranças, sucessão e cultura organizacional.',highlights:['Consultoria em Recursos Humanos, desenvolvimento de pessoas e transição de carreira','Frísia Cooperativa Agroindustrial: coordenação e estruturação da área de Desenvolvimento Humano','Implantação de programas de liderança, sucessão, avaliação de desempenho e pesquisa de clima'],education:'Psicologia pela UNAMA. Especialização em Gestão de Pessoas e Desenvolvimento Humano e Organizacional. Formação em Coaching, DISC e Axiologia.',contribution:'Conecta pessoas, cultura e estratégia para apoiar a atração, a retenção e o desenvolvimento de talentos, fortalecer lideranças e preparar a sucessão.'},
 andreza:{name:'Andreza Cristina Baroni Rosa',role:'Jurídico',photo:'andreza-baroni.webp',experience:'17+ anos de experiência profissional',summary:'Advogada empresarial com atuação em riscos jurídicos, contratos, propriedade intelectual, inovação e tecnologia.',highlights:['Sócia fundadora da Baroni Consultoria Jurídica Empresarial','Serviços jurídicos para mais de 400 empresas','Mentora no Distrito Spark CWB, Hotmilk e Observatório FIEP'],education:'Direito pela UFPR. Mestra em Propriedade Intelectual pelo PROFNIT/UFPR e LL.M. pela Universidade de Turim/OMPI. Pós-graduações em PI, Comércio Eletrônico, Direito Civil e Empresarial.',contribution:'Ajuda a antecipar vulnerabilidades e estruturar decisões, contratos, ativos intangíveis e novos modelos de negócio com segurança jurídica.'},
 luiz:{name:'Luiz Olivio Bortolli',role:'Tecnologia da Informação e Inovação',photo:'luiz-bortolli.webp',experience:'45+ anos de experiência profissional',summary:'Executivo sênior de TIC, logística integrada e inovação, com longa experiência em ambientes industriais complexos.',highlights:['22 anos como Gerente Geral de TI na DENSO do Brasil','New Holland: planejamento de sistemas, infraestrutura e Data Center','30 anos de atuação como conselheiro na AECIC'],education:'Administração. Mestre em Engenharia de Produção. Doutor em Administração. Formação de Conselheiro pelo IBGC.',contribution:'Apoia CEO e Board em decisões de investimento, arquitetura tecnológica, transformação digital e inovação, conectando estratégia, risco e execução.'},
 eduardo:{name:'Eduardo Vianna de Camargo Neves',role:'Marketing e Vendas',photo:'eduardo-neves.webp',experience:'30 anos de experiência profissional',summary:'Executivo e advisor em estratégia, marketing, vendas, tecnologia e desenvolvimento de mercados nacionais e internacionais.',highlights:['CNAD: mais de 130 clientes em 23 países','VP Marketing na Capzul','HPE: estratégia Go To Market de cibersegurança na América Latina'],education:'Bacharelado em Design Gráfico. Certificações ExO Coach, ExO Advisor e ExO Workshop Trainer pela Open EXO.',contribution:'Conecta decisões estratégicas às necessidades reais dos clientes, oportunidades de mercado e execução comercial para crescimento sustentável.'},
 amarildo:{name:'Amarildo Leal',role:'Gestão de Riscos',photo:'amarildo-leal.webp',experience:'35+ anos de experiência profissional',summary:'Executivo, advogado e empreendedor com experiência em gestão de riscos, crises, continuidade de negócios e ambientes críticos.',highlights:['32 anos como Delegado de Polícia Civil do Estado de São Paulo','Fundador da Leal Office 360','Experiência empresarial em segurança eletrônica e monitoramento'],education:'Advogado. Mestre em Direito e pós-graduado em Direito Tributário. Certificações ISO 31000, ISO 22301 e ISO/IEC 42001.',contribution:'Apoia o CEO na identificação de vulnerabilidades, análise de cenários complexos e antecipação das consequências de decisões relevantes.'},
 ricardo:{name:'Ricardo Geribello Anders',role:'Processos e Operações',photo:'ricardo-anders-aprovado.jpg',experience:'31 anos de experiência profissional',summary:'Conselheiro e executivo com experiência industrial, comercial, logística e administrativa, com foco em governança e eficiência.',highlights:['Renault do Brasil: liderança técnica, engenharia, fabricação e qualidade','Fator Solar: diretor comercial, técnico e administrativo','Luft Logistics: Gerente de Supply Chain'],education:'Engenharia Mecânica de Produção pela UFMG e Administração Internacional de Negócios pela UFPR. Pós em Finanças e Marketing. Formação de Conselheiros FDC e PMP.',contribution:'Traz visão sistêmica para direcionamento estratégico, eficiência operacional, projetos complexos e perenidade de empresas industriais e familiares.'},
 paulo:{name:'Paulo Roberto Bacchmi',role:'Finanças',photo:'paulo-bacchmi.webp',experience:'30 anos de experiência profissional',summary:'Executivo de controladoria, finanças e gestão empresarial, orientado à informação gerencial, resultados e geração de caixa.',highlights:['DENSO do Brasil: 14 anos em controladoria e finanças','Adami S/Madeiras: 14 anos em controladoria, finanças e assessoria à diretoria','Implantação de ERP, processos e planejamento estratégico'],education:'Bacharel em Ciências Contábeis, Administração e Direito. Compliance pela KPMG Business School. Formação em Conselho de Administração e Conselho Fiscal pelo IBGC.',contribution:'Apoia decisões para melhorar resultado, converter desempenho em caixa e fortalecer sustentabilidade financeira e governança.'}
};
const nav=document.querySelector('#navigation');
const toggle=document.querySelector('.menu-toggle');
function closeMenu(){nav.classList.remove('is-open');toggle.setAttribute('aria-expanded','false');toggle.setAttribute('aria-label','Abrir menu');}
toggle.addEventListener('click',()=>{const open=toggle.getAttribute('aria-expanded')!=='true';nav.classList.toggle('is-open',open);toggle.setAttribute('aria-expanded',String(open));toggle.setAttribute('aria-label',open?'Fechar menu':'Abrir menu');});
nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeMenu));
document.addEventListener('keydown',event=>{if(event.key==='Escape')closeMenu();});
document.addEventListener('click',event=>{if(!event.target.closest('.site-header'))closeMenu();});
const dialog=document.querySelector('#advisor-dialog');let previousFocus;
document.querySelectorAll('.advisor-open').forEach(button=>button.addEventListener('click',()=>{
 const a=advisors[button.dataset.advisor];previousFocus=button;
 ['name','role','experience','summary','education','contribution'].forEach(key=>document.getElementById('dialog-'+key).textContent=a[key]);
 const photo=document.querySelector('#dialog-photo');photo.src='assets/'+a.photo;photo.alt=a.name;photo.dataset.advisor=button.dataset.advisor;
 const list=document.querySelector('#dialog-highlights');list.replaceChildren(...a.highlights.map(item=>{const li=document.createElement('li');li.textContent=item;return li;}));
 dialog.showModal();document.body.style.overflow='hidden';dialog.scrollTop=0;document.querySelector('.dialog-copy').scrollTop=0;
}));
document.querySelector('.dialog-close').addEventListener('click',()=>dialog.close());
dialog.addEventListener('click',event=>{if(event.target===dialog){const rect=dialog.getBoundingClientRect();if(event.clientX<rect.left||event.clientX>rect.right||event.clientY<rect.top||event.clientY>rect.bottom)dialog.close();}});
dialog.addEventListener('close',()=>{document.body.style.overflow='';previousFocus?.focus({preventScroll:true});});
document.querySelectorAll('.journey details').forEach(item=>item.addEventListener('toggle',()=>{if(item.open)document.querySelectorAll('.journey details').forEach(other=>{if(other!==item)other.open=false;});}));
document.querySelectorAll('input[name="topic"]').forEach(input=>input.addEventListener('change',()=>{const text='Olá, Paulo. Gostaria de conversar sobre o Conselho Online. Meu interesse é: '+input.value+'.';document.querySelector('#contact-whatsapp').href='https://wa.me/5541996120774?text='+encodeURIComponent(text);}));
